#!/bin/sh
url='https://xkcd.com/'

usage()
{
cat << EOF
usage: xkcdl [-h] [-l] [-d NUM] [-a]
arguments:
	-h			show this help message and exit
	-n NUM		download specified comic by number
	-l			download latest comic
	-a			download all comics
EOF
}

download()
{
	wget --quiet -O "$1".html "$url""$1"
	image=$(grep "Image URL (for hotlinking/embedding):" "$1".html | sed 's/Image URL (for hotlinking\/embedding)\: //g')

	wget --quiet -O "$1"."${image##*.}" "$image"
	echo xkcd \#"$1" from "$image" downloaded

	rm "$1".html
}

latest()
{
	wget --quiet -O latest.html "$url"
	prev=$(grep "prev" latest.html | head -n 1 | awk '{print $3}' | sed 's/href="\///g' | sed 's/\/"//g')
	rm latest.html	

	echo $((prev+1))
}

while getopts 'hn:la' flag
do
	case "$flag"
	in
		h) usage ; exit ;;
		n) download ${OPTARG} ; exit ;;
		l) download $(latest) ; exit ;;
		a) for i in $(seq $(latest)); do download $i; done ; exit ;;
	esac
done

usage
